/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateCompany = /* GraphQL */ `
  subscription OnCreateCompany($id: String) {
    onCreateCompany(id: $id) {
      id
      name
      website
      addressLine1
      addressLine2
      city
      state
      zip
      country
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      allowUpdate
      employees {
        nextToken
        startedAt
      }
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onUpdateCompany = /* GraphQL */ `
  subscription OnUpdateCompany($id: String) {
    onUpdateCompany(id: $id) {
      id
      name
      website
      addressLine1
      addressLine2
      city
      state
      zip
      country
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      allowUpdate
      employees {
        nextToken
        startedAt
      }
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onDeleteCompany = /* GraphQL */ `
  subscription OnDeleteCompany($id: String) {
    onDeleteCompany(id: $id) {
      id
      name
      website
      addressLine1
      addressLine2
      city
      state
      zip
      country
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      allowUpdate
      employees {
        nextToken
        startedAt
      }
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onCreateEmployee = /* GraphQL */ `
  subscription OnCreateEmployee($id: String, $primaryManagerId: String) {
    onCreateEmployee(id: $id, primaryManagerId: $primaryManagerId) {
      id
      username
      profilePhoto
      email
      email_2
      firstName
      lastName
      phone
      phone_2
      addressLine1
      addressLine2
      city
      state
      zip
      country
      jobTitle
      payRates {
        name
        amount
        isHourly
        isDefault
      }
      companyId
      primaryManagerId
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      primaryManager {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      roles
      allowFull
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onUpdateEmployee = /* GraphQL */ `
  subscription OnUpdateEmployee($id: String, $primaryManagerId: String) {
    onUpdateEmployee(id: $id, primaryManagerId: $primaryManagerId) {
      id
      username
      profilePhoto
      email
      email_2
      firstName
      lastName
      phone
      phone_2
      addressLine1
      addressLine2
      city
      state
      zip
      country
      jobTitle
      payRates {
        name
        amount
        isHourly
        isDefault
      }
      companyId
      primaryManagerId
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      primaryManager {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      roles
      allowFull
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onDeleteEmployee = /* GraphQL */ `
  subscription OnDeleteEmployee($id: String, $primaryManagerId: String) {
    onDeleteEmployee(id: $id, primaryManagerId: $primaryManagerId) {
      id
      username
      profilePhoto
      email
      email_2
      firstName
      lastName
      phone
      phone_2
      addressLine1
      addressLine2
      city
      state
      zip
      country
      jobTitle
      payRates {
        name
        amount
        isHourly
        isDefault
      }
      companyId
      primaryManagerId
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      primaryManager {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      roles
      allowFull
      timeRecords {
        nextToken
        startedAt
      }
    }
  }
`;
export const onCreateTimeRecord = /* GraphQL */ `
  subscription OnCreateTimeRecord {
    onCreateTimeRecord {
      id
      companyId
      employeeId
      primaryManagerId
      timestampIn
      timestampOut
      photoIn
      photoOut
      noteIn
      noteOut
      rate {
        name
        amount
        isHourly
        isDefault
      }
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      employee {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      primaryManage {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
    }
  }
`;
export const onUpdateTimeRecord = /* GraphQL */ `
  subscription OnUpdateTimeRecord {
    onUpdateTimeRecord {
      id
      companyId
      employeeId
      primaryManagerId
      timestampIn
      timestampOut
      photoIn
      photoOut
      noteIn
      noteOut
      rate {
        name
        amount
        isHourly
        isDefault
      }
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      employee {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      primaryManage {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
    }
  }
`;
export const onDeleteTimeRecord = /* GraphQL */ `
  subscription OnDeleteTimeRecord {
    onDeleteTimeRecord {
      id
      companyId
      employeeId
      primaryManagerId
      timestampIn
      timestampOut
      photoIn
      photoOut
      noteIn
      noteOut
      rate {
        name
        amount
        isHourly
        isDefault
      }
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
      company {
        id
        name
        website
        addressLine1
        addressLine2
        city
        state
        zip
        country
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        allowUpdate
      }
      employee {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
      primaryManage {
        id
        username
        profilePhoto
        email
        email_2
        firstName
        lastName
        phone
        phone_2
        addressLine1
        addressLine2
        city
        state
        zip
        country
        jobTitle
        companyId
        primaryManagerId
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
        roles
        allowFull
      }
    }
  }
`;
